# Generated by Django 5.1.6 on 2025-03-20 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="experiences",
            field=models.ManyToManyField(
                help_text="На какие стажи расчитан курс",
                to="users.workexperience",
                verbose_name="Стаж",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="profession",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.profession",
                verbose_name="профессия",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="course",
            field=models.ForeignKey(
                help_text="Курс который обворачиваетсяивент",
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons.course",
                verbose_name="курс",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь которому будет назначен ивент",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="lessons.question",
                verbose_name="ответ",
            ),
        ),
    ]
