"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TEST_IMAGE_PATH = BASE_DIR.joinpath(*("lessons", "tests", "image.png"))
TEST_IMAGE_PATH_2 = BASE_DIR.joinpath(*("lessons", "tests", "image2.png"))


TEST_SCORM_PATH = BASE_DIR.joinpath(*("lessons", "scorm", "tests", "SCORM.zip"))


SCORM_MANIFEST_NAME = 'imsmanifest.xml'

SCORM_INDEX_NAME = 'index.html'

OS_PATH_ALT_SEP = '\\'


TYPE_CONTENTS = [
    ("Image", "Изображение"),
    ("Video", "Видео"),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv("DEBUG") else False


if not DEBUG:
    HOST = os.getenv("DJANGO_ALLOWED_HOSTS")
    ALLOWED_HOSTS = [HOST if HOST else "example.com"]
else:
    ALLOWED_HOSTS = ["*"]

# Application definition

# Джанго стандартные приложения.
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Наши приложения.
PROJECT_APPS = [
    "diary",
    "group",
    "lessons",
    "users",
]

# Приложения из вне.
THIRD_PARTY_APPS = [
    "drf_yasg",
    "drf_spectacular",
    "rest_framework",
    "rest_framework.authtoken",
    "authemail",
    "phonenumbers",
    "corsheaders",
    "channels",
]

INSTALLED_APPS = DJANGO_APPS + PROJECT_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = 'config.asgi.application'

# OpenAPI

OAS_PATH = BASE_DIR.joinpath("oas.yml")

API_VERSION = "api/v1/"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("ENGINE"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

# Rest framework

_page_paginator = "rest_framework.pagination.PageNumberPagination"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": _page_paginator,
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": (
    "django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ]
}

SPECTACULAR_SETTINGS = {
    "TITLE": "sdo_mm",
    "DESCRIPTION": "Система Дистанционного Обучения",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


STATUS_EVENTS = [
    (
        "finished",
        "Заканчивает",
    ),
    (
        "started",
        "Начано",
    ),
    (
        "expected",
        "Ожидает начало",
    ),
]

STATUS_COVERED = [
    (
        "done",
        "Успешно",
    ),
    (
        "failed",
        "Проваленно",
    ),
    (
        "process",
        "В процессе",
    ),
    (
        "expected",
        "Ожидает",
    )
]

VERSIONS_SCORM = [
    (
        'SCORM 1.0',
        '1.0',
    ),
    (
        'SCORM 1.1',
        '1.1',
    ),
    (
        'SCORM 1.2',
        '1.2',
    ),
    (
        '2004 1st Edition',
        'SCORM 2004.1',
    ),
    (
        '2004 2nd Edition',
        'SCORM 2004.2',
    ),
    (
        '2004 3rd Edition',
        'SCORM 2004.3',
    ),
    (
        '2004 4th Edition',
        'SCORM 2004.4',
    ),
]

TYPE_LESSON = [
    (
        "free",
        "свободный",
    ),
    (
        "linearly ",
        "линейный",
    )
]

EMAIL_FROM = os.getenv("DEFAULT_EMAIL_FROM")
EMAIL_BCC = os.getenv("DEFAULT_EMAIL_BCC")

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:5173",
]

CHANNELS_ALLOWED_WS_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:5173",
    "ws://localhost:8000",
    "ws://localhost:5173",
]
