export { default as PdfIcon } from './PdfIcon'
export { default as PngIcon } from './PngIcon'
export { default as JpgIcon } from './JpgIcon'
export { default as XlsIcon } from './XlsIcon'
export { default as DocIcon } from './DocIcon'
export { default as TxtIcon } from './TxtIcon'
