#!/bin/bash

set -o errexit
set -o nounset

rm -f './celerybeat.pid'

celery -A config \
  --broker=amqp://"${RABBITMQ_DEFAULT_USER}":"${RABBITMQ_DEFAULT_PASS}"@"${RMQ_HOST}":"${RMQ_PORT}" \
  beat -l INFO
