#!/bin/bash

set -o errexit
set -o nounset
4545454
celery -A config.celery.app \
  --broker=amqp://"${RABBITMQ_DEFAULT_USER}":"${RABBITMQ_DEFAULT_PASS}"@"${RMQ_HOST}":"${RMQ_PORT}" \
  beat \
  --loglevel=info