export * from './tabs/aboutCourse'
export * from './assignments-check'
export * from './tabs/assignments-grades'
export * from './tabs/program'
export * from './tabs/studentsList'
export * from './TrainingCenterCourse'
export * from './student-assignment'
