# Generated by Django 5.1.6 on 2025-03-14 09:31

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=256, verbose_name='Название профессии')),
                ('ru_name', models.CharField(max_length=256, verbose_name='Name Profession')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', users.models.IntegerRangeField(default=0, verbose_name='Стаж')),
            ],
            options={
                'verbose_name': 'Стаж',
                'verbose_name_plural': 'Стаж',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.profession'),
        ),
    ]
