# Generated by Django 5.1.6 on 2025-03-16 10:04

import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Шаг урока')),
                ('content_text', models.TextField(verbose_name='Контент шага урока')),
                ('serial', lessons.models.IntegerRangeField(default=1, verbose_name='Порядковый номер шага')),
            ],
            options={
                'verbose_name': 'Шаг урока',
                'verbose_name_plural': 'Шаги урока',
            },
        ),
    ]
