# Generated by Django 5.1.6 on 2025-03-16 10:11

import django.core.validators
import lessons.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='serial',
            field=lessons.models.IntegerRangeField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядковый номер шага'),
        ),
    ]
