# Generated by Django 5.1.6 on 2025-03-16 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_step_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='serial',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядковый номер шага'),
        ),
    ]
