# Generated by Django 5.1.6 on 2025-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_step_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='Контент шага урока'),
        ),
    ]
